In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer #Hàm xử lý dữ liệu nan
from sklearn.model_selection import train_test_split #Hàm chia bộ test
from sklearn.preprocessing import StandardScaler #Hàm phân phối chuẩn
from sklearn.tree import DecisionTreeRegressor #Cây phân loại
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

# XÂY DỰNG MACHINE LEARNING MODEL

* XỬ LÝ DỮ LIỆU
* MÃ HÓA DỮ LIỆU
* Machine Learning Model

In [2]:
df = pd.read_csv('D:\ML\Information_transform.csv')
df.head(5)

Title  New_Area  \
0  CHÍNH CHỦ BÁN NHÀ ĐƯỜNG BẾN LỘI, NHÀ KIÊN CỐ Đ...     60.00   
1  ĐẠI HẠ GIÁ 4 TỶ! CHÍNH CHỦ BÁN GẤP NHÀ MỚI XÂY...     98.00   
2  TÔI CẦN BÁN RẺ 1 TỶ NHÀ SỐ 9.15 PHỐ MINH KHAI,...     32.00   
3  CHÍNH CHỦ BÁN NHÀ TỰ XÂY VÀ ĐANG Ở - GÒ VẤP, H...     80.00   
4  BÁN NHÀ HẺM Ô TÔ ĐƯỜNG NGUYỄN KIỆM DT 56,73M2,...     56.73   

   New_Price_Per_Area  Bedroom  Bathroom      District          City  \
0          91670000.0        4         4      Bình Tân   Hồ Chí Minh   
1         188780000.0        0         0        Quận 2   Hồ Chí Minh   
2         246880000.0        3         4  Hai Bà Trưng        Hà Nội   
3         128750000.0        3         0        Gò Vấp   Hồ Chí Minh   
4          86370000.0        3         3        Gò Vấp   Hồ Chí Minh   

      New_Price  
0  5.500000e+09  
1  1.850000e+10  
2  7.900000e+09  
3  1.030000e+10  
4  4.900000e+09

In [3]:
df = df.drop_duplicates(subset =['Title'])

In [4]:
df2 = df.values[:,1:]
df2

array([[60.0, 91670000.0, 4, ..., 'Bình Tân', ' Hồ Chí Minh',
        5500000000.0],
       [98.0, 188780000.0, 0, ..., 'Quận 2', ' Hồ Chí Minh',
        18500000000.0],
       [32.0, 246880000.0, 3, ..., 'Hai Bà Trưng', ' Hà Nội',
        7900000000.0],
       ...,
       [32.0, 75000000.0, 3, ..., 'Hoài Đức', ' Hà Nội', 2400000000.0],
       [80.0, 85000000.0, 4, ..., 'Quận 8', ' Hồ Chí Minh', 6800000000.0],
       [55.0, 120000000.0, 4, ..., 'Nhà Bè', ' Hồ Chí Minh',
        6600000000.0]], dtype=object)

In [5]:
column = ['New_Area','New_Price_Per_Area','Bedroom','Bathroom','District','City','New_Price']
df2 = pd.DataFrame(df2,columns = column)
df2

New_Area New_Price_Per_Area Bedroom Bathroom      District          City  \
0        60.0         91670000.0       4        4      Bình Tân   Hồ Chí Minh   
1        98.0        188780000.0       0        0        Quận 2   Hồ Chí Minh   
2        32.0        246880000.0       3        4  Hai Bà Trưng        Hà Nội   
3        80.0        128750000.0       3        0        Gò Vấp   Hồ Chí Minh   
4       56.73         86370000.0       3        3        Gò Vấp   Hồ Chí Minh   
...       ...                ...     ...      ...           ...           ...   
1619     62.4        222760000.0       5        6     Phú Nhuận   Hồ Chí Minh   
1620    115.0         85220000.0       4        4  Ngũ Hành Sơn       Đà Nẵng   
1621     32.0         75000000.0       3        0      Hoài Đức        Hà Nội   
1622     80.0         85000000.0       4        3        Quận 8   Hồ Chí Minh   
1623     55.0        120000000.0       4        5        Nhà Bè   Hồ Chí Minh   

          New_Price  
0      5500000000.0  
1     18500000000.0  
2      7900000000.0  
3     10300000000.0  
4      4900000000.0  
...             ...  
1619  13900000000.0  
1620   9800000000.0  
1621   2400000000.0  
1622   6800000000.0  
1623   6600000000.0  

[1624 rows x 7 columns]

# 1. XỬ LÝ DỮ LIỆU :






 - XỬ LÝ DỮ LIỆU NGOẠI LAI

In [6]:
df2['Bedroom'].unique(),df2['Bathroom'].unique()

(array([4, 0, 3, 14, 2, 27, 5, 1, 6, 9, 29, 30, 21, 7, 10, 24, 62, 11, 38,
        8, 15, 18, 22, 13, 74, 26, 36, 20, 16, 25, 17, 12, 23, 100, 33, 51,
        40], dtype=object),
 array([4, 0, 3, 15, 2, 5, 1, 6, 9, 14, 30, 21, 7, 10, 25, 63, 13, 38, 8,
        50, 27, 17, 36, 20, 22, 18, 23, 12, 100, 11, 51], dtype=object))

In [18]:
group_bedroom = df2.groupby('Bedroom').count()['City']
group_bedroom.sort_values(ascending = False)
# DỮ LIỆU NGOẠI LAI ẢNH HƯỞNG ĐẾN MÔ HÌNH BEDROOM > 9

Bedroom
3      367
4      357
0      302
2      216
5      162
6       88
1       31
7       18
8       14
9       11
21       8
14       6
10       5
15       5
11       4
13       4
18       3
20       2
12       2
22       2
17       1
33       1
74       1
62       1
51       1
40       1
38       1
36       1
29       1
30       1
16       1
27       1
26       1
25       1
24       1
23       1
100      1
Name: City, dtype: int64

In [19]:
group_bathroom = df2.groupby('Bathroom').count()['City']
group_bathroom.sort_values(ascending = False)
# DỮ LIỆU NGOẠI LAI ẢNH HƯỞNG ĐẾN MÔ HÌNH BATHROOM > 9

Bathroom
0      466
4      266
3      251
2      237
5      178
1       75
6       60
7       21
8       15
13       6
21       6
15       6
9        5
14       4
10       4
11       3
23       2
17       2
18       2
20       2
22       2
25       2
38       1
63       1
51       1
50       1
12       1
36       1
30       1
27       1
100      1
Name: City, dtype: int64

In [20]:
df3 = df2.copy()
df3.head(5)

New_Area New_Price_Per_Area Bedroom Bathroom      District          City  \
0     60.0         91670000.0       4        4      Bình Tân   Hồ Chí Minh   
1     98.0        188780000.0       0        0        Quận 2   Hồ Chí Minh   
2     32.0        246880000.0       3        4  Hai Bà Trưng        Hà Nội   
3     80.0        128750000.0       3        0        Gò Vấp   Hồ Chí Minh   
4    56.73         86370000.0       3        3        Gò Vấp   Hồ Chí Minh   

       New_Price  
0   5500000000.0  
1  18500000000.0  
2   7900000000.0  
3  10300000000.0  
4   4900000000.0

In [21]:
df3.shape

(1624, 7)

In [22]:
df3.head(5)

New_Area New_Price_Per_Area Bedroom Bathroom      District          City  \
0     60.0         91670000.0       4        4      Bình Tân   Hồ Chí Minh   
1     98.0        188780000.0       0        0        Quận 2   Hồ Chí Minh   
2     32.0        246880000.0       3        4  Hai Bà Trưng        Hà Nội   
3     80.0        128750000.0       3        0        Gò Vấp   Hồ Chí Minh   
4    56.73         86370000.0       3        3        Gò Vấp   Hồ Chí Minh   

       New_Price  
0   5500000000.0  
1  18500000000.0  
2   7900000000.0  
3  10300000000.0  
4   4900000000.0

In [23]:
df3['Bedroom'] = df3['Bedroom'].replace(0,np.nan)
df3['Bathroom'] = df3['Bathroom'].replace(0,np.nan)
df3.head(5)

New_Area New_Price_Per_Area  Bedroom  Bathroom      District          City  \
0     60.0         91670000.0      4.0       4.0      Bình Tân   Hồ Chí Minh   
1     98.0        188780000.0      NaN       NaN        Quận 2   Hồ Chí Minh   
2     32.0        246880000.0      3.0       4.0  Hai Bà Trưng        Hà Nội   
3     80.0        128750000.0      3.0       NaN        Gò Vấp   Hồ Chí Minh   
4    56.73         86370000.0      3.0       3.0        Gò Vấp   Hồ Chí Minh   

       New_Price  
0   5500000000.0  
1  18500000000.0  
2   7900000000.0  
3  10300000000.0  
4   4900000000.0

# Hàm biến cột district, city thành chữ cái không dấu
from unidecode import unidecode
df4 = df3.copy()
df4.head(5)
def replace_data(x):
    x = x.replace(' ','')
    return x
df4['District'] = df4['District'].apply(unidecode)
df4['City'] = df4['City'].apply(unidecode)
df4['District'] = df4['District'].apply(replace_data)
df4['City'] = df4['City'].apply(replace_data)
df4

In [24]:
for col in df3.columns:
    missing_data = df3[col].isna().sum()
    missing_percent = round(missing_data/ len(df3) * 100,2)
    print(f'Column {col} has: {missing_percent}% missing data')

Column New_Area has: 0.0% missing data
Column New_Price_Per_Area has: 0.0% missing data
Column Bedroom has: 18.6% missing data
Column Bathroom has: 28.69% missing data
Column District has: 0.0% missing data
Column City has: 0.0% missing data
Column New_Price has: 0.18% missing data


- Cột Bedroom có 19.78% dữ liệu bị thiếu
- Cột Bathroom có 29.64% dữ liệu bị thiếu
- Cột New_Price có 0.18% dữ liệu bị thiếu nhưng đây là dữ liệu ngoại lai do cột giá không nằm trong (tỷ , triệu ) nên loại bỏ

In [25]:
df3.shape

(1624, 7)

In [26]:
df3['New_Price'] = df3['New_Price'].replace(np.nan, 0)
df3 = df3[df3['New_Price'] != 0]
df3.shape

(1621, 7)

    #2. Mã hóa dữ liệu

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [28]:
X = df3.iloc[:,:-1].values
X

array([[60.0, 91670000.0, 4.0, 4.0, 'Bình Tân', ' Hồ Chí Minh'],
       [98.0, 188780000.0, nan, nan, 'Quận 2', ' Hồ Chí Minh'],
       [32.0, 246880000.0, 3.0, 4.0, 'Hai Bà Trưng', ' Hà Nội'],
       ...,
       [32.0, 75000000.0, 3.0, nan, 'Hoài Đức', ' Hà Nội'],
       [80.0, 85000000.0, 4.0, 3.0, 'Quận 8', ' Hồ Chí Minh'],
       [55.0, 120000000.0, 4.0, 5.0, 'Nhà Bè', ' Hồ Chí Minh']],
      dtype=object)

In [29]:
Y = df3.iloc[:,-1:].values
Y

array([[5.50e+09],
       [1.85e+10],
       [7.90e+09],
       ...,
       [2.40e+09],
       [6.80e+09],
       [6.60e+09]])

In [30]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(sparse=False),[4,5])],remainder = 'passthrough')
X = ct.fit_transform(X)

In [31]:
X

array([[0.0, 0.0, 0.0, ..., 91670000.0, 4.0, 4.0],
       [0.0, 0.0, 0.0, ..., 188780000.0, nan, nan],
       [0.0, 0.0, 0.0, ..., 246880000.0, 3.0, 4.0],
       ...,
       [0.0, 0.0, 0.0, ..., 75000000.0, 3.0, nan],
       [0.0, 0.0, 0.0, ..., 85000000.0, 4.0, 3.0],
       [0.0, 0.0, 0.0, ..., 120000000.0, 4.0, 5.0]], dtype=object)

    #3 Xử lý dữ liệu Nan


In [32]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean') # Chuyển dữ liệu Null thành trung bình của từng cột
imputer.fit(X)
X = imputer.transform(X)
X

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        9.16700000e+07, 4.00000000e+00, 4.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.88780000e+08, 4.50720243e+00, 4.33073593e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.46880000e+08, 3.00000000e+00, 4.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        7.50000000e+07, 3.00000000e+00, 4.33073593e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        8.50000000e+07, 4.00000000e+00, 3.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.20000000e+08, 4.00000000e+00, 5.00000000e+00]])

# Machine Learning Model
    1. Chia mô hình ( 80% cho việc train , 20% cho việc test )
    2. Xử lý dữ liệu ngoại lai 

                                            #1 Chia mô hình

In [33]:
len(X),len(Y)

(1621, 1621)

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y ,train_size = 0.8,test_size = 0.2,random_state = 0)

In [35]:
len(X_train),len(Y_train) 

(1296, 1296)

In [36]:
len(X_test),len(Y_test)

(325, 325)

In [37]:
X_train, X_test,Y_train,Y_test

(array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.54390000e+08, 3.00000000e+00, 4.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.56430000e+08, 2.10000000e+01, 2.20000000e+01],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.33870000e+08, 5.00000000e+00, 3.00000000e+00],
        ...,
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.85180000e+08, 5.10000000e+01, 5.10000000e+01],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         2.32430000e+08, 4.50720243e+00, 4.33073593e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         2.10640000e+08, 4.50720243e+00, 4.33073593e+00]]),
 array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.0725e+08, 4.0000e+00,
         5.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.0263e+08, 6.0000e+00,
         5.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 8.8100e+07, 5.0000e+00,

                                            #2 Xử lý dữ liệu ngoại lai

In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [39]:
X_train,X_test

(array([[-3.93140567e-02, -2.77885007e-02, -1.83010445e-01, ...,
          4.03928385e-01, -3.04415366e-01, -7.59660786e-02],
        [-3.93140567e-02, -2.77885007e-02, -1.83010445e-01, ...,
          4.30835171e-01,  3.18914105e+00,  3.76767176e+00],
        [-3.93140567e-02, -2.77885007e-02, -1.83010445e-01, ...,
          1.33277766e-01,  8.37575693e-02, -2.89501514e-01],
        ...,
        [-3.93140567e-02, -2.77885007e-02, -1.83010445e-01, ...,
          8.10036208e-01,  9.01173509e+00,  9.96019939e+00],
        [-3.93140567e-02, -2.77885007e-02, -1.83010445e-01, ...,
          1.43324487e+00, -1.18877712e-02, -5.34223754e-03],
        [-3.93140567e-02, -2.77885007e-02, -1.83010445e-01, ...,
          1.14584346e+00, -1.18877712e-02, -5.34223754e-03]]),
 array([[-0.03931406, -0.0277885 , -0.18301044, ..., -0.21782942,
         -0.1103289 ,  0.13756936],
        [-0.03931406, -0.0277885 , -0.18301044, ..., -0.27876538,
          0.27784404,  0.13756936],
        [-0.03931406, -0.

                                    #3 Xây dựng mô hình máy học

In [40]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(random_state = 1)
dt_model.fit(X_train, Y_train)
price_predict = dt_model.predict(X_test)
len(price_predict),len(Y_test)

(325, 325)

In [41]:
df_ML = pd.DataFrame(list(zip(Y_test,price_predict)),columns = ['Price','Price Predict'])

In [42]:
df_ML 

Price  Price Predict
0    [7250000000.0]   7.100000e+09
1    [3900000000.0]   3.800000e+09
2    [3700000000.0]   3.600000e+09
3    [6700000000.0]   7.000000e+09
4    [5600000000.0]   5.000000e+09
..              ...            ...
320  [1500000000.0]   2.700000e+09
321  [6800000000.0]   6.500000e+09
322  [1520000000.0]   1.630000e+09
323  [3300000000.0]   3.300000e+09
324  [7600000000.0]   7.900000e+09

[325 rows x 2 columns]

In [43]:
df_ML['new_col'] = df_ML['Price Predict'] - df_ML['Price']
df_ML

Price  Price Predict         new_col
0    [7250000000.0]   7.100000e+09  [-150000000.0]
1    [3900000000.0]   3.800000e+09  [-100000000.0]
2    [3700000000.0]   3.600000e+09  [-100000000.0]
3    [6700000000.0]   7.000000e+09   [300000000.0]
4    [5600000000.0]   5.000000e+09  [-600000000.0]
..              ...            ...             ...
320  [1500000000.0]   2.700000e+09  [1200000000.0]
321  [6800000000.0]   6.500000e+09  [-300000000.0]
322  [1520000000.0]   1.630000e+09   [110000000.0]
323  [3300000000.0]   3.300000e+09           [0.0]
324  [7600000000.0]   7.900000e+09   [300000000.0]

[325 rows x 3 columns]

In [44]:
def bao_cao(do_chenh_lech):
    dem = 0
    for x in df_ML['new_col'].values:
        if abs(x) <= do_chenh_lech:
            dem+=1
            percent = round(dem/len(df_ML)*100,2)
    if do_chenh_lech == 0:
        print('Mô hình dư đoán chính xác giá nhà ở mức {} %'.format(percent))
    else:
        print('Mô hình dư đoán giá nhà ở dưới mức {} là : {} %'.format(do_chenh_lech,percent))

In [45]:
do_chenh_lech = [0,1000000,100000000,1000000000]
for x in do_chenh_lech:
    bao_cao(x)

Mô hình dư đoán chính xác giá nhà ở mức 14.77 %
Mô hình dư đoán giá nhà ở dưới mức 1000000 là : 15.38 %
Mô hình dư đoán giá nhà ở dưới mức 100000000 là : 41.23 %
Mô hình dư đoán giá nhà ở dưới mức 1000000000 là : 84.62 %
